language: elixir

elixir: 1.3.2

opt_release: 18.2

sudo: true

before_install:
  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.0.0.deb
  - sudo dpkg -i --force-confnew elasticsearch-5.0.0.deb
  - 'echo -e "index.number_of_shards: 1\nindex.number_of_replicas: 0" | sudo tee -a /etc/elasticsearch/elasticsearch.yml'
  - sudo service elasticsearch restart
  - sleep 15

script:
  - whereis elasticsearch
  - "elasticsearch -v"
  - mix test
