language:
  - elixir

elixir:
  - 1.3.2

opt_release:
  - 18.2

sudo:
  - false

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

env:
  global:
    - WAIT_FOR_ES=1
  matrix:
    - ES_VERSION=5.0.0

before_install:
  - mkdir /tmp/elasticsearch
  - wget -O - https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.0.0.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - /tmp/elasticsearch/bin/elasticsearch --daemonize --path.data /tmp

script  :
  - sleep 30
  - whereis elasticsearch
  - "elasticsearch -v"
  - "curl http://localhost:9200"
  - mix test
