language:
  - elixir

elixir:
  - 1.3.2

opt_release:
  - 18.2

sudo:
  - required

services:
  - docker

before_script:
  - docker pull elasticsearch
  - docker run -d -p 9200:9200 elasticsearch
  - sleep 60
  - docker ps

script:
  - docker ps
  - mix test
