language:
  - elixir

elixir:
  - 1.3.2

opt_release:
  - 18.2

services:
  - elasticsearch

addons:
  apt:
    sources:
      - elasticsearch-5.0
    packages:
      - elasticsearch  

script  :
  - sleep 30
  - mix test
  # - mix test
