language:
  - elixir

elixir:
  - 1.3.2

opt_release:
  - 18.2

sudo:
  - required

services:
  - docker

before_install:
  - docker pull elasticsearch

before_script:
  # - docker run -d -p 127.0.0.1:9500:9200 elasticsearch
  - docker -d run elasticsearch

script  :
  - sleep 30
  - docker ps
  # - mix test
