language:
  - elixir

elixir:
  - 1.3.2

opt_release:
  - 18.2

sudo:
  - false

env:
  global:
    - WAIT_FOR_ES=1
  matrix:
    - ES_VERSION=5.0.0

install:
  - mkdir /tmp/elasticsearch
  - wget -O - https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - /tmp/elasticsearch/bin/elasticsearch --daemonize --path.data /tmp

before_script:
  - sleep 10
  - curl http://127.0.0.1:9200

script  :
  - sleep 30
  - whereis elasticsearch
  - "elasticsearch -v"
  - "curl http://localhost:9200"
  - mix test
