language:
  - elixir

elixir:
  - 1.3.2

opt_release:
  - 18.2

sudo:
  - required

addons:
  apt:
    sources:
      - elasticsearch-5.0.0
    packages:
      - elasticsearch

services:
  - elasticsearch


script  :
  - sleep 30
  - whereis elasticsearch
  - "elasticsearch -v"
  - "curl http://localhost:9200"
  - mix test
  # - mix test
