language: elixir

sudo: required

elixir: 1.3.4

opt_release: 19.1.1

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  # update to java 8
  - sudo update-java-alternatives -s java-8-oracle
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - export MAX_HEAP_SIZE=128M
  - export HEAP_NEWSIZE=24M
  - java -version

  # install elasticsearch
  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.0.0.deb
  - sudo dpkg -i --force-confnew elasticsearch-5.0.0.deb
  - sudo service elasticsearch start
  - sleep 10

script:
  - mix test
  - mix dialyzer
