language:
  - elixir

elixir:
  - 1.3.2

opt_release:
  - 18.2

sudo:
  - required

services:
  - docker

before_install:
  - docker pull elasticsearch

script:
  - docker run -d elasticsearch
  - sleep 30
  - docker ps
  - mix test
