language:
  - elixir

elixir:
  - 1.3.2

opt_release:
  - 18.2

sudo:
  - required

services:
  - docker

before_install:
  - docker pull elasticsearch
  - docker run -d -p 127.0.0.1:9200:9200 elasticsearch
  - docker ps -a

before_script:
  - sleep 10

script:
  - mix test
